In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.max_columns", None)

print("Libraries Imported Successfully")

Libraries Imported Successfully

In [11]:
expenses = pd.read_csv("Expenses_clean.csv")
income = pd.read_csv("Income_clean.csv")

In [12]:
expenses.head()
income.head()

             date_time     category account  amount currency      tags
0  2025-11-29 00:00:00          Job  acct_1    49.0      BYN     tag_1
1  2025-11-29 00:00:00          Job  acct_1    18.0      BYN     tag_2
2  2025-11-29 00:00:00          Job  acct_1    32.0      BYN     tag_3
3  2025-11-29 00:00:00          Job  acct_1   109.0      BYN     tag_4
4  2025-11-28 00:00:00  Second work  acct_1   132.0      BYN  2th_work

In [13]:
print("Expense Dataset Shape :", expenses.shape)
print("Income Dataset Shape :", income.shape)

Expense Dataset Shape : (938, 6)
Income Dataset Shape : (349, 6)

In [15]:
print(expenses.columns)
print(income.columns)

Index(['date_time', 'category', 'account', 'amount', 'currency', 'tags'], dtype='object')
Index(['date_time', 'category', 'account', 'amount', 'currency', 'tags'], dtype='object')

In [16]:
expenses.isnull().sum()
income.isnull().sum()

date_time    0
category     0
account      0
amount       0
currency     0
tags         0
dtype: int64

In [17]:
print("Expense Duplicates :", expenses.duplicated().sum())
print("Income Duplicates :", income.duplicated().sum())

Expense Duplicates : 145
Income Duplicates : 0

In [18]:
expenses.describe()
income.describe()

            amount
count   349.000000
mean     76.300860
std     150.098066
min       2.000000
25%      20.000000
50%      36.000000
75%      67.000000
max    1506.000000

In [19]:
expenses["date_time"] = pd.to_datetime(expenses["date_time"])
income["date_time"] = pd.to_datetime(income["date_time"])

In [20]:
expenses.dtypes
income.dtypes

date_time    datetime64[ns]
category             object
account              object
amount              float64
currency             object
tags                 object
dtype: object

In [21]:
expenses["Year"] = expenses["date_time"].dt.year
expenses["Month"] = expenses["date_time"].dt.month
expenses["Month_Name"] = expenses["date_time"].dt.month_name()
expenses["Day"] = expenses["date_time"].dt.day
expenses["Day_Name"] = expenses["date_time"].dt.day_name()
expenses["Weekday"] = expenses["date_time"].dt.weekday

In [22]:
income["Year"] = income["date_time"].dt.year
income["Month"] = income["date_time"].dt.month
income["Month_Name"] = income["date_time"].dt.month_name()
income["Day"] = income["date_time"].dt.day
income["Day_Name"] = income["date_time"].dt.day_name()
income["Weekday"] = income["date_time"].dt.weekday

In [23]:
expenses.head()
income.head()

,date_time,category,account,amount,currency,tags,Year,Month,Month_Name,Day,Day_Name,Weekday
0,2025-11-29,Job,acct_1,49.0,BYN,tag_1,2025,11,November,29,Saturday,5
1,2025-11-29,Job,acct_1,18.0,BYN,tag_2,2025,11,November,29,Saturday,5
2,2025-11-29,Job,acct_1,32.0,BYN,tag_3,2025,11,November,29,Saturday,5
3,2025-11-29,Job,acct_1,109.0,BYN,tag_4,2025,11,November,29,Saturday,5
4,2025-11-28,Second work,acct_1,132.0,BYN,2th_work,2025,11,November,28,Friday,4

In [24]:
expenses.to_csv("Expenses_Processed.csv", index=False)
income.to_csv("Income_Processed.csv", index=False)

print("Processed datasets saved successfully!")

Processed datasets saved successfully!