In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
import joblib

import warnings
warnings.filterwarnings("ignore")

In [2]:
expenses = pd.read_csv("Expenses_Processed.csv")
income = pd.read_csv("Income_Processed.csv")

In [3]:
expenses["date_time"] = pd.to_datetime(expenses["date_time"])
income["date_time"] = pd.to_datetime(income["date_time"])

In [4]:
expenses.head()
income.head()

,date_time,category,account,amount,currency,tags,Year,Month,Month_Name,Day,Day_Name,Weekday
0,2025-11-29,Job,acct_1,49.0,BYN,tag_1,2025,11,November,29,Saturday,5
1,2025-11-29,Job,acct_1,18.0,BYN,tag_2,2025,11,November,29,Saturday,5
2,2025-11-29,Job,acct_1,32.0,BYN,tag_3,2025,11,November,29,Saturday,5
3,2025-11-29,Job,acct_1,109.0,BYN,tag_4,2025,11,November,29,Saturday,5
4,2025-11-28,Second work,acct_1,132.0,BYN,2th_work,2025,11,November,28,Friday,4

In [5]:
print(expenses.isnull().sum())
print()
print(income.isnull().sum())

date_time     0
category      0
account       0
amount        0
currency      0
tags          0
Year          0
Month         0
Month_Name    0
Day           0
Day_Name      0
Weekday       0
dtype: int64

date_time     0
category      0
account       0
amount        0
currency      0
tags          0
Year          0
Month         0
Month_Name    0
Day           0
Day_Name      0
Weekday       0
dtype: int64

In [6]:
expenses["category"] = expenses["category"].fillna("Unknown")
expenses["account"] = expenses["account"].fillna("Unknown")
expenses["currency"] = expenses["currency"].fillna("Unknown")
expenses["tags"] = expenses["tags"].fillna("No Tag")

In [7]:
income["category"] = income["category"].fillna("Unknown")
income["account"] = income["account"].fillna("Unknown")
income["currency"] = income["currency"].fillna("Unknown")
income["tags"] = income["tags"].fillna("No Tag")

In [8]:
expenses.drop_duplicates(inplace=True)
income.drop_duplicates(inplace=True)

print("Expense Shape :", expenses.shape)
print("Income Shape :", income.shape)

Expense Shape : (793, 12)
Income Shape : (349, 12)

In [9]:
expenses["Weekend"] = expenses["Day_Name"].isin(
    ["Saturday","Sunday"]
).astype(int)

income["Weekend"] = income["Day_Name"].isin(
    ["Saturday","Sunday"]
).astype(int)

In [10]:
expenses["Quarter"] = expenses["date_time"].dt.quarter
income["Quarter"] = income["date_time"].dt.quarter

In [11]:
category_encoder = LabelEncoder()

expenses["category"] = category_encoder.fit_transform(expenses["category"])

income["category"] = category_encoder.fit_transform(income["category"])

In [12]:
account_encoder = LabelEncoder()

expenses["account"] = account_encoder.fit_transform(expenses["account"])

income["account"] = account_encoder.fit_transform(income["account"])

In [13]:
currency_encoder = LabelEncoder()

expenses["currency"] = currency_encoder.fit_transform(expenses["currency"])

income["currency"] = currency_encoder.fit_transform(income["currency"])

In [14]:
tag_encoder = LabelEncoder()

expenses["tags"] = tag_encoder.fit_transform(expenses["tags"])

income["tags"] = tag_encoder.fit_transform(income["tags"])

In [15]:
expenses.head()

,date_time,category,account,amount,currency,tags,Year,Month,Month_Name,Day,Day_Name,Weekday,Weekend,Quarter
0,2025-11-30,6,0,114.0,0,1,2025,11,November,30,Sunday,6,1,4
1,2025-11-29,4,0,5.0,0,1,2025,11,November,29,Saturday,5,1,4
2,2025-11-27,11,1,1.0,0,1,2025,11,November,27,Thursday,3,0,4
3,2025-11-27,1,0,10.0,0,1,2025,11,November,27,Thursday,3,0,4
5,2025-11-26,1,2,2.0,0,1,2025,11,November,26,Wednesday,2,0,4

In [17]:
features = [
    "category",
    "account",
    "currency",
    "tags",
    "Year",
    "Month",
    "Day",
    "Weekday",
    "Weekend",
    "Quarter"
]

X = expenses[features]

y = expenses["amount"]

In [18]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [19]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [20]:
joblib.dump(scaler,"scaler.pkl")

['scaler.pkl']

In [21]:
joblib.dump(category_encoder,"category_encoder.pkl")
joblib.dump(account_encoder,"account_encoder.pkl")
joblib.dump(currency_encoder,"currency_encoder.pkl")
joblib.dump(tag_encoder,"tag_encoder.pkl")

['tag_encoder.pkl']